import { NextPage } from "next";

import Layout from "../components/Layout";
import HowItWorks from "../components/HowItWorks";

const imgStyle = {
  maxWidth: "440px",
};

const Home: NextPage = () => (
  <Layout>
    <h1>Lunch Buddies 🥙</h1>
    <p className="subhead">
      This app helps build relationships between teammates by scheduling
      participants into random groups for lunch. The @lunch_buddies_bot takes
      care of all the logistics.
    </p>
    <h2 className="newSection">Installation</h2>
    <p>Get started using Lunch Buddies with just a few clicks!</p>
    <a href="https://ahlfhssbq3.execute-api.us-west-2.amazonaws.com/production/api/v0/install">
      <img
        alt="Add to Slack"
        height="40"
        width="139"
        src="https://platform.slack-edge.com/img/add_to_slack.png"
        srcSet="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x"
      />
    </a>
    <HowItWorks />
    <h2 id="privacy" className="newSection">
      Privacy policy
    </h2>
    <h3>Data Retention Policy</h3>
    <p>
      Data is stored while Lunch Buddies is installed on your workspace.
      You can request the removal of your data at any time by making a
      request to {" "}<a href="mailto:support@lunchbuddiesapp.com">support@lunchbuddiesapp.com</a>{"."}
      We collect and retain the minimum data necessary for the app to function.
    </p>
    <h3>Data Archiving and Removal Policy</h3>
    <p>
      If you would like to access your user data, please email
      {" "}<a href="mailto:support@lunchbuddiesapp.com">support@lunchbuddiesapp.com</a>{" "}
      and request it. We will send a copy of your data within 30 days from the date of the request.
    </p>
    <p>
      You can submit a request to have your data deleted at any time after
      removing Lunch Buddies from your workspace. Send your
      request to {" "}<a href="mailto:support@lunchbuddiesapp.com">support@lunchbuddiesapp.com</a>{" "}
      and your data will be deleted within 30 days.
    </p>
    <h3>
      Data Storage Policy
    </h3>
    <p>
      Data is stored securely using AWS DynamoDB. All data is encrypted in transit
      with HTTPS over SSL and at rest. All data is stored in the US. The only data
      stored is the contact information of the user that installed the app, the
      slack channel ids for the channels where polls are generated by user action,
      and the user ids of the users that respond to polls.
      No other identifying user information is stored.
    </p>
    <h2 id="support" className="newSection">
      Support
    </h2>
    <p className="supportBottom">
      If you have any questions or feature requests, please send me an email at{" "}
      <a href="mailto:quinn@lunchbuddiesapp.com">quinn@lunchbuddiesapp.com</a>.
    </p>
    <style jsx>{`
      h1 {
        font-weight: 800;
        font-size: 50px;
        margin-top: 5rem;
      }

      .subhead {
        font-size: 25px;
      }

      .newSection {
        margin-top: 4rem;
      }

      .supportBottom {
        margin-bottom: 5rem;
      }
    `}</style>
  </Layout>
);

export default Home;
